version: '3'

services:
  wso2is:
    build: .
    image: identityorg/wso2is58:1.0
    ports:
      - 443:9443
    depends_on:
      - mysql
    volumes:
      - repository:/home/wso2carbon/wso2is-5.8.0/repository/
      - tenants:/home/wso2carbon/wso2is-5.8.0/tenants/
    networks: 
      wso2cluster: {}
      default: {}

  mysql:
    image: mysql:5
    networks:
      - default
    ports:
       - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
      - mysqldata:/var/lib/mysql/

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "80:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]

volumes:
  repository:
  mysqldata:
  tenants:

networks:
  default:
  wso2cluster:
    ipam: 
      driver: default
      config:
        - subnet: 172.28.1.0/16
